type = "web_pixel_extension"
name = "xenon-capture"

runtime_context = "strict"

[settings]
type = "object"

[settings.fields.apiKey]
name = "API Key"
description = "XenonView API Key"
type = "single_line_text_field"

[settings.fields.debug]
name = "Debug"
description = "XenonView Debug Logging"
type = "single_line_text_field"
